//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdresyKontrahentow
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AdresyKontrahentow()
        {
            this.Kontrahenci1 = new HashSet<Kontrahenci>();
        }
    
        public int IdAdresuKontrahenta { get; set; }
        public Nullable<int> IdKontrahenta { get; set; }
        public string KodPocztowy { get; set; }
        public string Kraj { get; set; }
        public string Miasto { get; set; }
        public string Ulica { get; set; }
        public string NrDomu { get; set; }
        public string NrLokalu { get; set; }
        public Nullable<bool> CzyAktywne { get; set; }
        public Nullable<int> IdRaport { get; set; }
    
        public virtual Kontrahenci Kontrahenci { get; set; }
        public virtual Raport Raport { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kontrahenci> Kontrahenci1 { get; set; }
    }
}
