//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Faktury
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Faktury()
        {
            this.PozycjeFaktury3 = new HashSet<PozycjeFaktury>();
        }
    
        public int IdFaktury { get; set; }
        public Nullable<System.DateTime> DataWystawienia { get; set; }
        public string Miejscowosc { get; set; }
        public Nullable<System.DateTime> DataSprzedazy { get; set; }
        public Nullable<int> NumerFaktury { get; set; }
        public Nullable<int> IdPracownikaWystawiajacego { get; set; }
        public Nullable<int> IdPracownikaSprawdzajacego { get; set; }
        public Nullable<int> IdNabywca { get; set; }
        public Nullable<int> IdSprzedawca { get; set; }
        public Nullable<int> IdPlatnika { get; set; }
        public Nullable<System.DateTime> DataPlatnosci { get; set; }
        public Nullable<System.DateTime> TerminPlatnosci { get; set; }
        public string NumerRachunkuBankowego { get; set; }
        public string Adnotacje { get; set; }
        public Nullable<bool> CzyAktywny { get; set; }
        public Nullable<int> IdRaportu { get; set; }
        public Nullable<int> IdRodzajPlatnosci { get; set; }
        public Nullable<int> IdPozycjeFaktury { get; set; }
    
        public virtual Kontrahenci Kontrahenci { get; set; }
        public virtual Kontrahenci Kontrahenci1 { get; set; }
        public virtual Kontrahenci Kontrahenci2 { get; set; }
        public virtual PozycjeFaktury PozycjeFaktury { get; set; }
        public virtual PozycjeFaktury PozycjeFaktury1 { get; set; }
        public virtual PozycjeFaktury PozycjeFaktury2 { get; set; }
        public virtual Pracownicy Pracownicy { get; set; }
        public virtual Pracownicy Pracownicy1 { get; set; }
        public virtual Raport Raport { get; set; }
        public virtual RodzajePlatnosci RodzajePlatnosci { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PozycjeFaktury> PozycjeFaktury3 { get; set; }
    }
}
