//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Komisy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Komisy()
        {
            this.Pojazdy = new HashSet<Pojazdy>();
        }
    
        public int IdKomisu { get; set; }
        public Nullable<int> IdAdresuKomisu { get; set; }
        public string OsobaKontaktowa { get; set; }
        public string NrKomisu { get; set; }
        public string NazwaKomisu { get; set; }
        public string Telefon1 { get; set; }
        public string Telefon2 { get; set; }
        public string Email1 { get; set; }
        public string Email2 { get; set; }
        public Nullable<System.DateTime> DataDodania { get; set; }
        public Nullable<int> IdRaportu { get; set; }
        public Nullable<bool> CzyAktywne { get; set; }
        public string Adnotacje { get; set; }
    
        public virtual AdresyKomisow AdresyKomisow { get; set; }
        public virtual Raport Raport { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pojazdy> Pojazdy { get; set; }
    }
}
