//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kontrahenci
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kontrahenci()
        {
            this.AdresyKontrahentow = new HashSet<AdresyKontrahentow>();
            this.Faktury = new HashSet<Faktury>();
            this.Faktury1 = new HashSet<Faktury>();
            this.Faktury2 = new HashSet<Faktury>();
            this.Pojazdy = new HashSet<Pojazdy>();
        }
    
        public int IdKontrahenta { get; set; }
        public string Imie { get; set; }
        public string Nazwisko { get; set; }
        public string Nazwa { get; set; }
        public string OsobaKontaktowa { get; set; }
        public string PESEL { get; set; }
        public string NIP { get; set; }
        public string REGON { get; set; }
        public Nullable<int> IdAdresuKontrahenta { get; set; }
        public string Telefon1 { get; set; }
        public string Telefon2 { get; set; }
        public string Email1 { get; set; }
        public string Email2 { get; set; }
        public string RachunekBankowy { get; set; }
        public Nullable<bool> CzyAktywny { get; set; }
        public Nullable<int> IdRaportu { get; set; }
        public Nullable<bool> Dostawca { get; set; }
        public string Adnotacje { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdresyKontrahentow> AdresyKontrahentow { get; set; }
        public virtual AdresyKontrahentow AdresyKontrahentow1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Faktury> Faktury { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Faktury> Faktury1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Faktury> Faktury2 { get; set; }
        public virtual Raport Raport { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pojazdy> Pojazdy { get; set; }
    }
}
