//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KomisEntities : DbContext
    {
        public KomisEntities()
            : base("name=KomisEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdresyKomisow> AdresyKomisow { get; set; }
        public virtual DbSet<AdresyKontrahentow> AdresyKontrahentow { get; set; }
        public virtual DbSet<AdresyPracownikow> AdresyPracownikow { get; set; }
        public virtual DbSet<DokladnyTypPojazdu> DokladnyTypPojazdu { get; set; }
        public virtual DbSet<Faktury> Faktury { get; set; }
        public virtual DbSet<Klimatyzacja> Klimatyzacja { get; set; }
        public virtual DbSet<Kolory> Kolory { get; set; }
        public virtual DbSet<Komisy> Komisy { get; set; }
        public virtual DbSet<Kontrahenci> Kontrahenci { get; set; }
        public virtual DbSet<Marka> Marka { get; set; }
        public virtual DbSet<ModelPojazdu> ModelPojazdu { get; set; }
        public virtual DbSet<OgolnyTypPojazdu> OgolnyTypPojazdu { get; set; }
        public virtual DbSet<Pojazdy> Pojazdy { get; set; }
        public virtual DbSet<PozycjeFaktury> PozycjeFaktury { get; set; }
        public virtual DbSet<Pracownicy> Pracownicy { get; set; }
        public virtual DbSet<Raport> Raport { get; set; }
        public virtual DbSet<RodzajePlatnosci> RodzajePlatnosci { get; set; }
        public virtual DbSet<StawkiVat> StawkiVat { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypSilnika> TypSilnika { get; set; }
        public virtual DbSet<Wyposazenie> Wyposazenie { get; set; }
        public virtual DbSet<Zdjecia> Zdjecia { get; set; }
        public virtual DbSet<ZmianyCeny> ZmianyCeny { get; set; }
    }
}
