//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PozycjeFaktury
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PozycjeFaktury()
        {
            this.Faktury = new HashSet<Faktury>();
            this.Faktury1 = new HashSet<Faktury>();
            this.Faktury2 = new HashSet<Faktury>();
        }
    
        public int IdPozycjiFaktury { get; set; }
        public Nullable<int> IdFaktury { get; set; }
        public Nullable<int> IdPojazdu { get; set; }
        public string Nazwa { get; set; }
        public Nullable<decimal> Cena { get; set; }
        public Nullable<int> IdStawkaVat { get; set; }
        public string ZwolnieniaOdPodatkow { get; set; }
        public Nullable<bool> CzyAktywny { get; set; }
        public Nullable<int> IdRaportu { get; set; }
        public Nullable<double> Rabat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Faktury> Faktury { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Faktury> Faktury1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Faktury> Faktury2 { get; set; }
        public virtual Faktury Faktury3 { get; set; }
        public virtual Pojazdy Pojazdy { get; set; }
        public virtual Raport Raport { get; set; }
        public virtual StawkiVat StawkiVat { get; set; }
    }
}
