//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wyposazenie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Wyposazenie()
        {
            this.Pojazdy = new HashSet<Pojazdy>();
        }
    
        public int IdWyposazenia { get; set; }
        public Nullable<bool> ABS { get; set; }
        public Nullable<bool> ElektryczneSzybyPrzenie { get; set; }
        public Nullable<bool> ElektryczneSzybyTylnie { get; set; }
        public Nullable<bool> GniazdoAUX { get; set; }
        public Nullable<bool> ISOFIX { get; set; }
        public Nullable<bool> CD { get; set; }
        public Nullable<bool> GniazdoSD { get; set; }
        public Nullable<bool> USB { get; set; }
        public Nullable<bool> Tempomat { get; set; }
        public Nullable<bool> CzyAktywne { get; set; }
        public Nullable<int> IdRaportu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pojazdy> Pojazdy { get; set; }
        public virtual Raport Raport { get; set; }
    }
}
